version: '3.0'
services:
  rent-car:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./.env:/opt/app/.env
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    env_file: .env

